query SelectAllUserPessoal {
  usuario_pessoal {
    values {
      id
      data_criacao
      data_nascimento
      descricao
      email
      hash_senha
      idade
      nome
      sexo
      sobrenome
    }
  }
}
